# Generated by Django 4.0.4 on 2022-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=18)),
                ('birthday', models.DateField()),
                ('password', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(null=True, upload_to='')),
                ('email', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': '유저',
                'ordering': ['uid', 'uname'],
            },
        ),
    ]
