# Generated by Django 4.0.4 on 2022-05-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_users_profile_image_users_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
