# Generated by Django 4.0.4 on 2022-05-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calenders', '0003_alter_calenders_table'),
        ('Users', '0003_alter_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(to='Users.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='personal_calender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_calender', to='Calenders.calenders', unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
