# Generated by Django 4.0.4 on 2022-05-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calenders', '0003_alter_calenders_table'),
        ('Users', '0004_users_friends_users_personal_calender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='personal_calender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_calender', to='Calenders.calenders'),
        ),
    ]
