# Generated by Django 4.0.4 on 2022-05-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calenders',
            table='Calenders',
        ),
    ]
