# Generated by Django 4.0.4 on 2022-05-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calenders', '0002_alter_calenders_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calenders',
            table='Calender',
        ),
    ]
