# Generated by Django 4.0.4 on 2022-05-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mcontent', models.CharField(max_length=100)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '메시지',
                'ordering': ['send_time'],
            },
        ),
    ]
