# Generated by Django 4.0.4 on 2022-05-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_users_friends_users_personal_calender_and_more'),
        ('Messages', '0003_alter_messages_options_messages_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='receiver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Users.users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Users.users'),
        ),
    ]
