# Generated by Django 4.0.4 on 2022-05-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=100)),
                ('gcontent', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': '그룹',
                'ordering': ['gid', 'gname'],
            },
        ),
    ]
