# Generated by Django 4.0.4 on 2022-05-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calenders', '0003_alter_calenders_table'),
        ('Groups', '0004_alter_groups_group_calender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_calender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_calender', to='Calenders.calenders'),
        ),
    ]
